{% set version = "0.7.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-goeveg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/goeveg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/goeveg/goeveg_{{ version }}.tar.gz
  sha256: 83c65cdb7aa23e8b5659424c93b58d39c8750e92e3c9e351b5eac94e08a0abdd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-hmisc
    - r-fields
    - r-mgcv
    - r-vegan
  run:
    - r-base
    - r-hmisc
    - r-fields
    - r-mgcv
    - r-vegan

test:
  commands:
    - $R -e "library('goeveg')"           # [not win]
    - "\"%R%\" -e \"library('goeveg')\""  # [win]

about:
  home: https://github.com/fvlampe/goeveg/
  license: GPL-2.0-or-later
  summary: A collection of functions useful in (vegetation) community analyses and ordinations. Includes automatic species selection for ordination diagrams, species response curves and rank-abundance curves as well as calculation and sorting of synoptic tables.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: goeveg
# Type: Package
# Title: Functions for Community Data and Ordinations
# Version: 0.4.2
# Date: 2018-11-22
# Author: Friedemann Goral [aut, cre], Jenny Schellenberg [aut]
# Maintainer: Friedemann Goral <fgoral@gwdg.de>
# Description: A collection of functions useful in (vegetation) community analyses and ordinations. Includes automatic species selection for ordination diagrams, species response curves and rank-abundance curves as well as calculation and sorting of synoptic tables.
# License: GPL (>= 2)
# LazyData: TRUE
# Depends: R (>= 2.10)
# Imports: vegan, fields, mgcv, Hmisc, cluster
# Suggests: vegdata, BiodiversityR
# URL: http://github.com/fgoral/goeveg
# BugReports: http://github.com/fgoral/goeveg/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-11-22 13:39:44 UTC; fgoral
# Repository: CRAN
# Date/Publication: 2018-11-22 14:00:21 UTC
