appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: I9zmZsZYcXkD7iREIYsG72rhHpPkHCQDU/gxpsAXt6hm6RdX68mRHte/3iJH7L6eHJAp44Pb/4BDp0rnME5Fa3AyLlyf6dNfVXvIur6md9u9QHspuSib21XYEnpq0Df/0OiSMIgSrCTtVTuu8yL6jMIqoVR/6YInNBuSeoebCKagOjnVCZUlyD5eDsMeo3/NheNlw0O5uIyn3R00SJSn0D51ajCYpW2q0oPj5wHV7wEvidZPnDfIYF9CerH3abnwmt1lHSiu39AbfOoirg0eYtMhypS/QDNW5SOgn1EKGX+N3A46h+XoH40p+0sgT5G929xTO0jzwOSRy5/AiQt3uxLFxSWaZLpl3AiT4T/zCAmVi7eIx4exWyPHD3VYyxumM5Ox95RWJGAgN7KzE0/nts0xBH1W0aoZYbZKDU4MKefxPF8pJrb4pB3bS2ViHS4x/Zt18uJtRdAPx7vTHbyAezZJ5B/TjJ6/Swbs2xpRBRgVt3k1qpj5JGKZ+M8vChupcFylrJ6GMYdvR+UWufAdxGYwDUHNivnp2qVRsV0peIUA5tFEZWIKSGLnRzIM2IWHEfdZAoSkM2BW+Ij2gzD+e/I9vAXV6nC5+Y4sIcy0b3IR255vgBABYuA9JrbNhKD24VOlXtTPsoYqUrUw1HAPzP2ZN2xFycxCqKQuShQfbJ0=
conda_forge_output_validation: true
